owner: ${{ github.repository_owner }}
git-base-url: https://api.github.com
git-upload-url: https://uploads.github.com
index-path: ./index.yaml
charts-repo: https://${{ github.repository_owner }}.github.io/Tarnfui