image:
  repository: ghcr.io/{{ .Values.github.repository_owner | default "your-org" }}/tarnfui
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

github:
  repository_owner: ""
