name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Matches semantic versioning tags (e.g., v1.2.3)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tarnfui:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/tarnfui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Setup Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      # Update Helm chart version and appVersion
      - name: Update Chart version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          sed -i "s/version: .*$/version: $VERSION/" charts/tarnfui/Chart.yaml
          sed -i "s/appVersion: .*$/appVersion: \"$VERSION\"/" charts/tarnfui/Chart.yaml

      # Publish Helm chart to GitHub Pages
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/tarnfui --destination .cr-release-packages/

      - name: Upload Helm chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
          config: .github/cr.yaml